Repository vigneshshettyin/Meetly, pull requests merged in 2022-04, with the labels that each got.

#31 Added shimmer layout for RecyclerViews
  .idea/misc.xml
  app/src/main/java/com/vs/meetly/MainActivity.kt
  app/src/main/java/com/vs/meetly/MeetingFilter.kt
  app/src/main/java/com/vs/meetly/MeetingViewDetail.kt
  app/src/main/java/com/vs/meetly/SupportActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_meeting_filter.xml
  app/src/main/res/layout/activity_meeting_view_detail.xml
  app/src/main/res/layout/activity_support.xml
  app/src/main/res/layout/shimmer_item_meeting.xml
  app/src/main/res/layout/shimmer_item_support.xml
  app/src/main/res/layout/user_meeting_list_shimmer.xml
Labels: GSSoC22, Level2

#32 Removed unnecessary toast of "Logged In" on opening app
  app/src/main/java/com/vs/meetly/MainActivity.kt
  app/src/main/java/com/vs/meetly/SplashActivity.kt
Labels: GSSoC22, Level1

#37 Search Bug fixed
  .idea/misc.xml
  app/src/main/java/com/vs/meetly/MainActivity.kt
Labels: GSSoC22, Level1

#39 Fixed bug -> If not allowed permission, then app does not open.
  app/src/main/java/com/vs/meetly/SplashActivity.kt
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, GSSoC22, Level2

#40 Added EditText validation errors
  app/src/main/java/com/vs/meetly/LoginActivity.kt
  app/src/main/java/com/vs/meetly/RegisterActivity.kt
Labels: GSSoC22, Level1

#42 Enabled Firebase Google Authentication
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/vs/meetly/LoginActivity.kt
  app/src/main/res/drawable-v21/google_icon.png
  app/src/main/res/layout/activity_login.xml
Labels: GSSoC22, Level2
