Repository vigneshshettyin/Meetly, pull requests merged in 2022-03, with the labels that each got.

#17 Register Screen fields' whitespace issue fixed
  app/src/main/java/com/vs/meetly/RegisterActivity.kt
Labels: GSSoC22, Level1

#20 Hide keyboard in auth
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/vs/meetly/ForgotPassActivity.kt
  app/src/main/java/com/vs/meetly/LoginActivity.kt
  app/src/main/java/com/vs/meetly/RegisterActivity.kt
  app/src/main/res/layout/activity_devs.xml
  app/src/main/res/layout/activity_register.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: GSSoC22, Level2

#28 Modified Team Section
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/vs/meetly/DevsActivity.kt
  app/src/main/java/com/vs/meetly/adapters/TeamAdapter.kt
  app/src/main/java/com/vs/meetly/modals/Team.kt
  app/src/main/java/com/vs/meetly/retrofit/TeamAPI.kt
  app/src/main/res/layout/activity_devs.xml
  app/src/main/res/layout/list_item.xml
  app/src/main/res/layout/shimmer_item.xml
  app/src/main/res/raw/team.json
Labels: GSSoC22, Level3
